name: GitHub Actions Demo
on: [push]
jobs:
  Lint-Test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repostitory
        uses: actions/checkout@v2
      - name: Run Linting
        run: echo "Running Linting test..."
          npm run lint
        env:
          CI: true
